### ISSUE TITLE
Error gathering Drive files. TypeError: Cannot read properties of null (reading 'getName').

### ISSUE THREAD

**Issue by wtip** [thebrandonc/gdrive-file-auditor#1]
Could the script be updated to skip shared files where the properties can not be read?

_Something went wrong...._

```
Error gathering Drive files. TypeError: Cannot read properties of null (reading 'getName').
Error occured on the following file: https://docs.google.com/document/d/1me6XFeYDgLgfQCPUz5skvltJK2pApS41cC7DOvuTX2E/edit?usp=drivesdk
```

**Comment by thebrandonc** [comment]
Hey William, thanks for bringing this to my attention. I'll update the script to handle that case

**Comment by k-3rb** [comment]
Was this ever updated? Getting the same error trying to run.

**Comment by thebrandonc** [comment]
Hey all, this is now fixed
